import path from "path";

export const PAGES = [
  { page: "logon",
    path: "login",
    icon: "/login.svg",
    active: true,
  },
  {page: "message log",
    path: "logs",
    icon: "/forum.svg",
    active: false,
  },
  {page: "request",
    path: "request",
    icon: "/chat_add_on.svg",
    active: false,
  },
  {page: "reports",
    path: "reports",
    icon: "/analytics.svg",
    active: false,
  },
  {page: "emergency",
    path: "emergency",
    icon: "/emergency.svg",
    active: false,
  },
  {page: "settings",
    path: "settings",
    icon: "/settings.svg",
    active: false,
  },
  {page: "print",
    path: "print",
    icon: "/print.svg",
    active: false,
  },
];                                                      
