import { GlobalProvider } from "@/context/GlobalContext";
import "./globals.css";
import { FlightProvider } from "@/context/FlightContext";
import { ErrorProvider } from "@/context/ErrorContext";
import { LoadProvider } from "@/context/LoadContext";
import { LogsProvider } from "@/context/LogsContext";

export const metadata = {
  title: "CPDLC AIR",
  description: "Generated by Irina",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-hidden bg-[url('/bg-5.png')]">
        <GlobalProvider>
          <FlightProvider>
            <LoadProvider>
              <LogsProvider>
                <ErrorProvider>{children}</ErrorProvider>
              </LogsProvider>
            </LoadProvider>
          </FlightProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
